# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a42b92b8e4731aa204058874ab6ef57331a0354b0d7a8d9d58d46ebeecbe1110e95198696152cf2984090ad9a1a05be33ca84f15bf8571f3339f896750df800

test:
  secret_key_base: 0852aa286bc44c686477e14bdee20bfa00b37cf61e2c1cf2fd85bf7c8e69e9da8430057b3d900dd179f836bac9f0240b77f2570fa5c0aa2dbc00bd3031502c60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
